# -------------------------------------------------------
# Copyright (c) [2024] FASNY
# All rights reserved
# -------------------------------------------------------
# Automatic kids session management
# -------------------------------------------------------
# Nadège LEMPERIERE, @6th september 2024
# Latest revision: 6th september 2024
# -------------------------------------------------------

name: Robotics Session Registration Tool Pull Request Check

on:
    pull_request:
        types: [ assigned, opened, synchronize, reopened ]

jobs:


    check:
        name: Analyze Package
        runs-on: ubuntu-latest
        container:
          image: docker://python:latest
          options: --entrypoint /bin/bash
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Installing dependencies
              run: pip install -r requirements-test.txt

            - name: Linting module
              run: pylint manager.py

            - name: Run pip-audit to check for vulnerabilities
              run: pip-audit -r requirements-test.txt --format json

    test:
        name: Testing Package
        runs-on: ubuntu-latest
        container:
          image: docker://python:latest
          options: --entrypoint /bin/bash
        needs: [check]
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Get token
              env:
                TOKEN: ${{secrets.MANTABOTS_TOKEN}}
              shell: bash
              run: echo "$TOKEN" >> token.json

            - name: Launching tests
              run: ./scripts/robot.sh -l WARN -d tests