# -------------------------------------------------------
# Copyright (c) [2024] FASNY
# All rights reserved
# -------------------------------------------------------
# Automatic kids session management
# -------------------------------------------------------
# Nadège LEMPERIERE, @6th september 2024
# Latest revision: 17th september 2024
# -------------------------------------------------------

name: MantaBots Robotics Session Registration

on:
    schedule:
        - cron: '0 4 * * *'  # Runs at midnight UTC every day
    workflow_dispatch:  # Allows manual trigger from GitHub Actions
    repository_dispatch: # Allows  trigger from GitHub API

jobs:

    register:
        name: Launching registration process
        runs-on: ubuntu-latest
        container:
          image: docker://python:3.12.6
          options: --entrypoint /bin/bash
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Get token
              env:
                TOKEN: ${{secrets.MANTABOTS_TOKEN}}
              shell: bash
              run: echo "$TOKEN" >> token.json

            - name: Launch registration
              env:
                PASSWORD: ${{secrets.MANTABOTS_MAIL_PASSWORD}}
                RECIPIENT: ${{vars.MANTABOTS_RECIPIENT}}
                SENDER: ${{vars.MANTABOTS_SENDER}}
              run: ./scripts/register.sh -p ${PASSWORD} -t ${RECIPIENT} -f ${SENDER} -c conf/conf-mantabots.json -a Microsoft

